package fr.rowlaxx.binanceapi.core.futures.trade;

public enum IncomeTypes {

	TRANSFER, 
	WELCOME_BONUS, 
	REALIZED_PNL, 
	FUNDING_FEE, 
	COMMISSION, 
	INSURANCE_CLEAR, 
	REFERRAL_KICKBACK, 
	COMMISSION_REBATE, 
	DELIVERED_SETTELMENT, 
	COIN_SWAP_DEPOSIT, 
	COIN_SWAP_WITHDRAW
	
}
